services: 
  db:
    #go fetch the image called postgres from the docker registry.
    image: postgres
    #it will set this environment variable for the image. 
    #this is what the postgres image uses to set the initial password. 
    environment:
      - POSTGRES_PASSWORD=dontwanttostudy

  #importer is the name of the service  will import the data. 
  importer:
  #our new service is not in the docker regristry. 
  #So use the current directory as the build-context. This directory needs to contain the Dockerfile.
    build:
      context: .
